name: trivy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '20 3 * * 5'

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    name: trivy
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout GitHub code
        uses: actions/checkout@v3

      - name: Read Keycloak version from .env file
        id: getversion
        run: echo "::set-output name=version::$(grep 'KC_VERSION' .env | cut -d'=' -f2 | cut -d'#' -f1)"

      - name: Scan Keycloak with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'quay.io/keycloak/keycloak:${{ steps.getversion.outputs.version }}'
          format: 'sarif'
          output: 'trivy-keycloak.sarif'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Upload scan Keycloak results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-keycloak.sarif'
